### PR TITLE
patch: Use Dependabot to bump CLI version

### PR DESCRIPTION
**Pull request by maggie0002**
To significantly speed up the container build process the CLI is now being pulled from the Balena CLI repo rather than building it from scratch (https://github.com/balena-io/deploy-to-balena-action/pull/167). This is a massive improvement in speed, but means that to upgrade the CLI we would have to change the version number set in an `ARG` in the Dockerfile manually rather than rely on the Dependabot updates to track updates and create pull requests. 

As we never like having to do things manually that can be done automatically, this pull request adds a `./cli/package.json` that has just one package in it, the CLI. Then it uses the Dockerfile and `jq` to read that package.json file (not with NPM - the package file is never used, it is just accessed as JSON), gets the version number and places it in the URL for the CLI to be pulled. That way the dependabot function is restored.

Alternatives considered:

- Including it in the current package.json, but then adds to the build time again.
- Including it in a separate section of the package.json from `dependencies` or `development`, but then out of the ordinary scope of what Dependabot checks
- Using the GitHub API to pull the latest CLI version, but then can't version the CLI with the action.

Change-type: minor

### CODE REVIEW

**Comment by klutchell** [comment]
> A quick update on why this is just sitting here. I haven't tested yet that dependabot picks up the new setting, would need to push to a test repo. But wondering whether this is something better fixed by Renovate magic instead of dependabot and maybe this PR isn't the way go go? @klutchell

Agreed that this would better be solved with the Renovate regex manager like we did for the SUPERVISOR_VERSION here.
https://github.com/balena-os/meta-balena/blob/master/.github/renovate.json#L14-L21

**Comment by maggie0002** [comment]
> > A quick update on why this is just sitting here. I haven't tested yet that dependabot picks up the new setting, would need to push to a test repo. But wondering whether this is something better fixed by Renovate magic instead of dependabot and maybe this PR isn't the way go go? @klutchell
> 
> Agreed that this would better be solved with the Renovate regex manager like we did for the SUPERVISOR_VERSION here. https://github.com/balena-os/meta-balena/blob/master/.github/renovate.json#L14-L21

Ok, I took the dependabot reference out, so this now just adds `cli/package.json` which Renovate could point to, and it changes the Dockerfile to read from that .json file when building the container.

**Comment by klutchell** [comment]
@maggie0002 I don't think this even needs the package.json file, we can just write a renovate rule to update the ARG directly in the Dockerfile and keep it simple. Might as well scrap this PR and start a new one.

**Comment by maggie0002** [comment]
> @maggie0002 I don't think this even needs the package.json file, we can just write a renovate rule to update the ARG directly in the Dockerfile and keep it simple. Might as well scrap this PR and start a new one.

Renovate can do all that?? Fantastic.

**Pull request closed without merging**
