### PR TITLE
Update balena-cli to v13.1.13

### PR DESCRIPTION
**Pull request by klutchell**
Update balena-cli from 12.55.11 to 13.1.13

Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>
Resolves: https://github.com/balena-io/deploy-to-balena-action/issues/110

### CODE REVIEW

**Comment by klutchell** [comment]
@balena-ci retest

**Comment by stathismor** [comment]
@balena-ci retest

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Pull request merged**
